spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogifydb
    username: blogify
    password: blogify123

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/blogify-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
